version: '3.9'

services:
  fastapi_app:
    container_name: web_server
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - SY_network
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
    depends_on:
      redis:
        condition: service_healthy
      sql_server:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=mssql+pyodbc://SA:StrongP@ssw0rd!@sql_server/mydatabase?driver=ODBC+Driver+18+for+SQL+Server

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - SY_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongP@ssw0rd!"
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver_data:/var/opt/mssql
    networks:
      - SY_network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P StrongP@ssw0rd! -Q 'SELECT 1'"]
      interval: 30s
      timeout: 20s
      retries: 10

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: sql_server
    networks:
      - SY_network
    ports:
      - "8080:8080"

networks:
  SY_network:
    external: true
